version: "2"

services:
 openplc:
   image: ioexpert/armv7-openplc
   restart: always
   privileged: true
   network_mode: host
   ports:
     - 8080:8080
     - 502:502
   devices:
     - "/dev/gpiomem:/dev/gpiomem"
 nodered:
   image: ioexpert/armv7-nodered
   restart: always
   privileged: false
   network_mode: host
   ports:
     - 1880:1880
 dashboard:
   image: ioexpert/armv7-nodered-dashboard-hdmi
   restart: always
   privileged: true
   network_mode: host
   ports:
     - 5900:5900
   devices:
     - "/dev/tty0:/dev/tty0"
     - "/dev/tty2:/dev/tty2"
     - "/dev/fb0:/dev/fb0"
     - "/dev/input:/dev/input"
     - "/dev/snd:/dev/snd"
   environment:
     - SSHPORT=22
